//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WonderApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Companies = new HashSet<Company>();
            this.Deals = new HashSet<Deal>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> LocationId { get; set; }
        public bool Archived { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<Deal> Deals { get; set; }
        public virtual Location Location { get; set; }
    }
}
