//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WonderApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public long Id { get; set; }
        public string User_Id { get; set; }
        public int Deal_Id { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Deal Deal { get; set; }
    }
}
