//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WonderApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Deals = new HashSet<Deal>();
            this.Cities = new HashSet<City>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geography { get; set; }
    
        public virtual ICollection<Deal> Deals { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<City> Cities { get; set; }
    }
}
