//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WonderApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationEmail
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Sent { get; set; }
        public string RecipientEmail { get; set; }
        public string RecipientName { get; set; }
        public Nullable<int> Template_Id { get; set; }
    
        public virtual Template Template { get; set; }
    }
}
