//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WonderApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public Template()
        {
            this.NotificationEmails = new HashSet<NotificationEmail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Thumbnail { get; set; }
        public string File { get; set; }
    
        public virtual ICollection<NotificationEmail> NotificationEmails { get; set; }
    }
}
