//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WonderApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WonderAppModelContainer : DbContext
    {
        public WonderAppModelContainer()
            : base("name=WonderAppModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deal> Deals { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<Cost> Costs { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<Age> Ages { get; set; }
        public virtual DbSet<UserPreference> UserPreferences { get; set; }
        public virtual DbSet<NotificationEmail> NotificationEmails { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
    
        public virtual ObjectResult<GetAges_Result> GetAges(string userId, Nullable<int> cityId, Nullable<int> priority)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("cityId", cityId) :
                new ObjectParameter("cityId", typeof(int));
    
            var priorityParameter = priority.HasValue ?
                new ObjectParameter("priority", priority) :
                new ObjectParameter("priority", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAges_Result>("GetAges", userIdParameter, cityIdParameter, priorityParameter);
        }
    
        public virtual ObjectResult<GetTags_Result> GetTags(string userId, Nullable<int> cityId, Nullable<int> priority)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("cityId", cityId) :
                new ObjectParameter("cityId", typeof(int));
    
            var priorityParameter = priority.HasValue ?
                new ObjectParameter("priority", priority) :
                new ObjectParameter("priority", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTags_Result>("GetTags", userIdParameter, cityIdParameter, priorityParameter);
        }
    
        public virtual ObjectResult<GetWonders_Result> GetMyWonders(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWonders_Result>("GetMyWonders", userIdParameter);
        }
    
        public virtual ObjectResult<GetAges_Result> GetWonderAges(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAges_Result>("GetWonderAges", userIdParameter);
        }
    
        public virtual ObjectResult<GetTags_Result> GetWonderTags(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTags_Result>("GetWonderTags", userIdParameter);
        }
    
        public virtual ObjectResult<GetAges_Result> GetAgesForWonder(Nullable<int> wonderId)
        {
            var wonderIdParameter = wonderId.HasValue ?
                new ObjectParameter("wonderId", wonderId) :
                new ObjectParameter("wonderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAges_Result>("GetAgesForWonder", wonderIdParameter);
        }
    
        public virtual ObjectResult<GetTags_Result> GetTagsForWonder(Nullable<int> wonderId)
        {
            var wonderIdParameter = wonderId.HasValue ?
                new ObjectParameter("wonderId", wonderId) :
                new ObjectParameter("wonderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTags_Result>("GetTagsForWonder", wonderIdParameter);
        }
    
        public virtual ObjectResult<GetWonders_Result> GetWonder(Nullable<int> wonderId)
        {
            var wonderIdParameter = wonderId.HasValue ?
                new ObjectParameter("wonderId", wonderId) :
                new ObjectParameter("wonderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWonders_Result>("GetWonder", wonderIdParameter);
        }
    
        public virtual ObjectResult<GetWonders_Result> GetWonders(string userId, Nullable<int> cityId, Nullable<int> priority)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("cityId", cityId) :
                new ObjectParameter("cityId", typeof(int));
    
            var priorityParameter = priority.HasValue ?
                new ObjectParameter("priority", priority) :
                new ObjectParameter("priority", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWonders_Result>("GetWonders", userIdParameter, cityIdParameter, priorityParameter);
        }
    }
}
